/*
 * This source file was generated by the Gradle 'init' task
 */
package org.server;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        DBController dbController = new DBController("jdbc:sqlite:main.db");
        System.out.println(dbController.getUser("yzk5", true));
    }
}
